name: sourcebytes_bot_sdk
description: "An Indo-sakura chatbot package from source byte to train your AI model and seamlessly give you a polished output."
version: 0.0.1
homepage: https://github.com/source-byte/sourcebytes-bot-flutter-sdk
repository: https://github.com/source-byte/sourcebytes-bot-flutter-sdk

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.5.1
  http: ^1.2.2
  build_runner: ^2.4.11
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  flutter_riverpod: ^2.5.1
  intl: ^0.20.2
  device_info_plus: ^10.1.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  network_info_plus: ^6.0.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  lottie: ^3.3.1
  cached_network_svg_image: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen: ^5.10.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # To add assets to your package, add an assets section, like this:
  assets:
    - lib/assets/lottie/chat_typing_lottie.json
    - lib/assets/icon/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gilroy
      fonts:
        - asset: lib/assets/font/Gilroy/Gilroy-Light.ttf
          weight: 300
        - asset: lib/assets/font/Gilroy/Gilroy-Regular.ttf
          weight: 400
        - asset: lib/assets/font/Gilroy/Gilroy-Medium.ttf
          weight: 500
        - asset: lib/assets/font/Gilroy/Gilroy-Bold.ttf
          weight: 700
        - asset: lib/assets/font/Gilroy/Gilroy-Heavy.ttf
          weight: 900
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
